# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Lyricist
tagline:             'SpotifyxGenius Taste Profiling'
description:         "How I deployed my own <a href=\"
https://open.spotify.com/playlist/0NEdo2eVecBFoETj0JITPd?si=A4Y3IObJS5KkU-ef-VIwkw\">
playlist</a> generator to recommend me songs I'd like based on their lyrics!"
url:                 'http://rohit11may.github.io/lyricist/'
baseurl:             ''
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              Rohit Prasad
  url:               https://instagram.com/_thelittlebird
  email:             rohit11may@gmail.com

# Custom vars
version:             1.0.0
gems:
  - jekyll-paginate
